
```{bash, eval=F}

cd /beegfs/data/merel/GND/dN_dS/coevol/Runs

for Aln in Aln*
do
  
  cd  /beegfs/data/merel/GND/dN_dS/coevol/Runs/$Aln #!
  
  for X in "1" "2"
  do
  
    ~/coevol/data/readcoevol  +mean -x 300 1 1300 $Aln.$X > $Aln.$X.log
    
  done
done

~/coevol/data/tracecomp
# Formatting

cd /beegfs/data/merel/GND/dN_dS/coevol/Runs
echo -e "dS\tomega\tGS\tDev\tDNA\tHelitron\tLINE\tLTR\tSINE\tTEs\tENCprime\tSCUO" > rownames.txt
echo -e ".\.\ndS\nomega\nGS\nDev\nDNA\nHelitron\nLINE\nLTR\nSINE\nTEs\nENCprime\nSCUO\n" > colnames.txt

cd /beegfs/data/merel/GND/dN_dS/coevol/Runs

for Aln in Aln*
do
  
  cd  /beegfs/data/merel/GND/dN_dS/coevol/Runs/$Aln #!
  cat ../rownames.txt > pp.csv
  cat ../rownames.txt > cc.csv

  grep 'posterior probs' -A 13 $Aln.1.cov | head -n 14 | tail -n 12 >> pp.csv
  grep 'correlation coefficients' -A 13 $Aln.1.cov | head -n 14 | tail -n 12 >> cc.csv

  paste ../colnames.txt pp.csv > tmp && mv tmp pp.csv
  paste ../colnames.txt cc.csv > tmp && mv tmp cc.csv

  #Keeping Y, then X
  cut -f 1,4,6,7,8,9,10,11 pp.csv | awk '{if ($1==".\\." || $1=="omega" || $1=="Dev" || $1=="ENCprime" || $1=="SCUO") print $0}' > tmp && mv tmp pp.csv
  cut -f 1,4,6,7,8,9,10,11 cc.csv | awk '{if ($1==".\\." || $1=="omega" || $1=="Dev" || $1=="ENCprime" || $1=="SCUO") print $0}' > tmp && mv tmp cc.csv

  #proxy categ pp cc Aln 
  Rscript ../Format.R $Aln
  
  #Adding min, max, median GC3
  GC3=`Rscript /beegfs/data/merel/GND/Alignments/get_GC3.R /beegfs/data/merel/GND/Alignments/$Aln.txt`
  Min=`echo $GC3 | cut -f 2 -d ' '`
  Max=`echo $GC3 | cut -f 3 -d ' '`
  Median=`echo $GC3 | cut -f 4 -d ' '`

  awk -v Min=$Min \
  -v Max=$Max \
  -v Median=$Median '{print $0" "Min" "Max" "Median}'   df.csv > tmp && mv tmp df.csv
done

cd /beegfs/data/merel/GND/dN_dS/coevol/Runs
cat */df.csv > df.csv

scp merel@pbil-gates.univ-lyon1.fr:/beegfs/data/merel/GND/dN_dS/coevol/Runs/df.csv ~/gnd/dN_dS/coevol/
grep -v Aln30 ~/gnd/dN_dS/coevol/df.csv > tmp && mv tmp ~/gnd/dN_dS/coevol/df.csv

```{r, eval=F}
library(dplyr)
df <- read.table("~/gnd/dN_dS/coevol/df.csv", quote="\"", comment.char="")
colnames(df) <- c("proxy","categ","pp","cc","Aln","min_GC3","max_GC3","median_GC3")

#No Random (i.e. Aln > )

Random_list <- paste("Aln",20:29,collapse=NULL, sep="")

df <- df %>%
  mutate(
  concat=ifelse(
    grepl(paste(Random_list,collapse='|'),Aln),"Random","NotRandom")) %>%
  mutate(significant=ifelse(pp>0.975 | pp<0.025,"pp>0.975\nor\npp<0.025",
  ifelse(pp>0.95  | pp<0.5, "pp>0.95\nor\npp<0.05","ns")))
library(ggplot2)


for (CATEG in unique(df$categ)){
  print(CATEG)
  

MIN=min(df$cc[df$categ==CATEG ])
MAX=max(df$cc[df$categ==CATEG ])
RANGE=MAX-MIN
MIN_X=MIN-RANGE/100
MAX_X=MAX+RANGE/100

NotRandom_omega <- ggplot(df[df$concat!="Random" & df$categ==CATEG & df$proxy=="omega",],
  aes(x=median_GC3,
      y=cc,
      color=significant)) + 
  geom_point(size=1) +
  theme_bw()+
  theme(legend.position="none",
        text=element_text(size=9),
        legend.title=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank())+
  ylim(c(MIN_X,MAX_X))+
  scale_colour_manual(values=c("darkgray","#ff5252ff","#810000ff"))
#legend.position="none",
Random_omega <- ggplot(df[df$concat=="Random" & df$categ==CATEG & df$proxy=="omega",],           aes(x=proxy,
      y=cc)) + 
  geom_boxplot()+
  geom_jitter(aes(color=significant), size=1) +
  theme_bw()+
  theme(legend.position="none",
        text=element_text(size=9),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.x=element_blank())+
  ylim(c(MIN_X,MAX_X))+
  scale_colour_manual(values=c("darkgray","#ff5252ff","#810000ff"))+
  scale_x_discrete(labels=c("Random"))

NotRandom_ENC<- ggplot(df[df$concat!="Random" & df$categ==CATEG & df$proxy=="ENCprime",],
  aes(x=median_GC3,
      y=cc,
      color=significant)) + 
  geom_point(size=1) +
  theme_bw()+
  theme(legend.position="none",
        text=element_text(size=9),
        axis.title.x=element_blank(),
        axis.title.y=element_blank())+
  ylim(c(MIN_X,MAX_X))+
  scale_colour_manual(values=c("darkgray","#ff5252ff","#810000ff"))

Random_ENC <- ggplot(df[df$concat=="Random" & df$categ==CATEG & df$proxy=="ENCprime",],
aes(x=proxy,
      y=cc)) + 
  geom_boxplot()+
  geom_jitter(aes(color=significant), size=1) +
  theme_bw()+
  theme(legend.position="none",
        text=element_text(size=9),
        legend.title=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.x=element_blank())+
  ylim(c(MIN_X,MAX_X))+
  scale_colour_manual(values=c("darkgray","#ff5252ff","#810000ff"))+
  scale_x_discrete(labels=c("Random"))

NotRandom_SCUO<- ggplot(df[df$concat!="Random" & df$categ==CATEG & df$proxy=="SCUO",],
  aes(x=median_GC3,
      y=cc,
      color=significant)) + 
  geom_point(size=1) +
  theme_bw()+
  theme(legend.position="none",
        text=element_text(size=9),
        axis.title.x=element_blank(),
        axis.title.y=element_blank())+
  ylim(c(MIN_X,MAX_X))+
  scale_colour_manual(values=c("darkgray","#ff5252ff","#810000ff"))

Random_SCUO <- ggplot(df[df$concat=="Random" & df$categ==CATEG & df$proxy=="SCUO",],
aes(x=proxy,
      y=cc)) + 
  geom_boxplot()+
  geom_jitter(aes(color=factor(significant)),size=1) +
  theme_bw()+
  theme(legend.position="none",
        text=element_text(size=9),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.x=element_blank())+
  ylim(c(MIN_X,MAX_X))+
  scale_colour_manual(values=c("darkgray","#ff5252ff","#810000ff"))+
  scale_x_discrete(labels=c("Random"))


legend <- ggplot(df,
  aes(x=median_GC3,
      y=cc,
      color=significant)) + 
  geom_point(size=1) +
  theme_bw()+
  theme(text=element_text(size=9),
  legend.text.align = 0.5,
  legend.title=element_blank(),
  legend.spacing.y = unit(0.25, 'cm'),
  legend.background = element_blank(),
  legend.key = element_rect(color="black",size=0.25 ),
  legend.box.background = element_blank())+ #element_rect(colour = "black", size=0.25)
  guides(color = guide_legend(byrow = TRUE))+
  scale_colour_manual(values=c("darkgray","#ff5252ff","#810000ff")) #, name="pp:"
  
legend <- cowplot::get_legend(legend)
library("cowplot")

All <- ggdraw() +
  draw_plot(NotRandom_omega, x = 0.02, y = 0.02 , width = .25, height = 0.92) +
  draw_plot(Random_omega, x = 0.27, y = 0.02, width = .05, height = 0.92) + 
  draw_plot(NotRandom_ENC, x = 0.36, y = 0.02 , width = .25, height = 0.92) +
  draw_plot(Random_ENC, x = 0.61, y = 0.02, width = .05, height = 0.92) +
  draw_plot(NotRandom_SCUO, x = 0.69, y = 0.02 , width = .24, height = 0.92) +
  draw_plot(Random_SCUO, x = 0.94, y = 0.02, width = .05, height = 0.92)+
  draw_text("Concatenate GC3", x = 0.5, y = 0.015, size=9)+
  draw_text("Correlation coefficient", angle = 90, x= 0.015, size=9) +
  draw_text(paste("Correlation", CATEG,"~ omega"), y=0.95, x= 0.02+0.025, hjust=0, size=9) +
  draw_text(paste("Correlation", CATEG,"~ ENC'"), y=0.95, x= 0.36+0.025, hjust=0, size=9) +
  draw_text(paste("Correlation", CATEG,"~ SCUO"), y=0.95, x= 0.69+0.025, hjust=0, size=9)
  
All_legend <- plot_grid(All, legend, rel_widths = c(10, 1))

ggsave(plot=All_legend, paste("~/gnd/dN_dS/coevol/",CATEG,".pdf",sep=""),width=20,height=10,units="cm")
}
```

# Adding GC, min, max, median
echo "Aln0 0.309 0.516 0.457
Aln1
Aln2
Aln3
Aln4
Aln5
Aln6
Aln7
Aln8
Aln9
Aln10
Aln11
Aln12
Aln13
Aln14
Aln15
Aln16
Aln17
Aln18
Aln19
Aln20
Aln21
Aln22
Aln23
Aln24
Aln25
Aln26
Aln27
Aln28
Aln29"


cd /beegfs/data/merel/GND/dN_dS/coevol/Runs



```
 
 