

```{r, eval=F}

library(ape)
library(caper)
library(dplyr)
#library(knitr)
#library(kableExtra)

#Importing tree
tree <- read.tree("/home/vmerel/gnd/Tree/root_droso_tree_MF")
tree$node.label <- NULL #VM

#Importing traits
Traits <- read.delim("~/gnd/ancov/Traits.tsv")

#An empty data.frame to fill
df <- data.frame(
  X = character(),
  Y = character(),
  PGLs_p = numeric(),
  PGLs_cor = numeric())



ID <- Traits$Id
Traits <- Traits %>% dplyr::select(-c("Id","Dev"))
X_Names <- colnames(Traits)
Y_Names <- colnames(Traits)

#Restoring NA
Traits[Traits == -1] <- NA


for (X_Name in X_Names){
  
  Y_Names <- Y_Names[-1]
  
  for (Y_Name in Y_Names){

    X <- Traits[,colnames(Traits) %in% X_Name]
    Y <- Traits[,colnames(Traits) %in% Y_Name]
    
    data <- cbind(as.character(ID), log(X), log(Y))
    colnames(data) <- c("ID","Yaxis","Xaxis")
    data <- as.data.frame(data)
    
    data$Yaxis <- as.numeric(data$Yaxis)
    data$Xaxis <- as.numeric(data$Xaxis)
    
    pgls_data = comparative.data(
      tree,
      data, 
      ID,      vcv=TRUE)
    
    PGLS <- pgls(Yaxis ~ Xaxis, pgls_data) #, lambda='ML', delta='ML'
    summary_PGLS <- summary(PGLS)
    
    PGLs_P <- summary_PGLS$coefficients[2,4]
    PGLs_COR <- summary_PGLS$coefficients[2,1]
    tmp <- data.frame(X = X_Name,
                      Y = Y_Name,
                      PGLs_p = PGLs_P,
                      PGLs_cor = PGLs_COR)
                      
    df <- rbind(df,tmp)
    

    
  }
}

df$PGLs_p <- p.adjust(df$PGLs_p, method="BH")
#saved <- df 

